### ISSUE TITLE
Canopsis installation

### ISSUE THREAD

**Issue by gcoeugnet** [capensis/canopsis#226]
Hi,

I try to install canopsis following indications given [here](https://github.com/capensis/canopsis/wiki/Install-from-sources).

I'm facing problem during build-install.sh when requests python library is compiled. It gives me this error : NameError: name 'CERT_NONE' is not defined when compiling "requests-1.1.0"

Indeed, regarding the web, this version of requests seems to have [a bug](http://stackoverflow.com/questions/14919557/how-to-get-urllib3-and-requests-working-with-jython-2-7-beta-1) which was fixed in other version. I've tested that by installing lastest version of "requests" tarball which then compil sucessfully. But, canopsis installation failed later because requests-1.1.0 is not installed. Installation process doesn't accept the last "requests" version.

Could you tell me what i'm supposed to do to install sakura with requests-1.1.0 knowing it contains a bug ? I try to post my question in the forum community but never succeeded in registering...

Thanks,
Regards

**Comment by linkdd** [comment]
Hello,

Can you give us more informations please?

 * what distribution (with version) are you building on?
 * what branch are you building?

We used to have this problem when Python was built without SSL support due to the missing package ``libssl-dev``.

So it seems that you're on an unsupported distribution by Canopsis (see the content of: ``sources/extra/dependencies`` to support a custom distribution).

**Comment by gcoeugnet** [comment]
Hello linkdd,

I try to install canopsis on an Ubuntu 15.10. The support of this version isn't clearly indicated in the [install page](https://github.com/capensis/canopsis) : "Easy way (on Debian 6 & ulterior, CentOS 6, Ubuntu 12.04 & ulterior 64Bits):"

Regarding your post, I've just try to reinstall canopsis with libssl-dev installed but still failed with the same error : 
```
Searching for requests
Best match: requests 1.1.0
Processing requests-1.1.0.tar.gz
Running requests-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-V8cAwS/requests-1.1.0/egg-dist-tmp-tpdRkG
Traceback (most recent call last):
  File "/opt/canopsis/bin/easy_install", line 8, in <module>
    load_entry_point('setuptools==0.6c11', 'console_scripts', 'easy_install')()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1712, in main
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/opt/canopsis/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/opt/canopsis/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/canopsis/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 446, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 476, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 655, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 930, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 919, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 62, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 105, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 64, in <lambda>
  File "setup.py", line 6, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/__init__.py", line 52, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/utils.py", line 23, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/compat.py", line 7, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/packages/__init__.py", line 3, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/packages/urllib3/__init__.py", line 16, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/packages/urllib3/connectionpool.py", line 45, in <module>
  File "/tmp/easy_install-V8cAwS/requests-1.1.0/requests/packages/urllib3/util.py", line 293, in <module>
NameError: name 'CERT_NONE' is not defined
```

I guess the branch used is "master". Here is how I get the version : 
```
root@canopsis:/opt# git clone https://github.com/capensis/canopsis.git
Cloning into 'canopsis'...
remote: Counting objects: 76877, done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 76877 (delta 48), reused 0 (delta 0), pack-reused 76752
Receiving objects: 100% (76877/76877), 29.81 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (45033/45033), done.
Checking connectivity... done.
root@canopsis:/opt# cd canopsis/
root@canopsis:/opt/canopsis# git submodule init
Submodule 'sources/externals' (https://git.canopsis.net/canopsis/canopsis-externals.git) registered for path 'sources/externals'
Submodule 'sources/webcore' (https://git.canopsis.net/canopsis/canopsis-webcore.git) registered for path 'sources/webcore'
root@canopsis:/opt/canopsis# git submodule update
Cloning into 'sources/externals'...
remote: Counting objects: 10694, done.
remote: Compressing objects: 100% (6381/6381), done.
remote: Total 10694 (delta 3975), reused 10458 (delta 3881)
Receiving objects: 100% (10694/10694), 480.95 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (3975/3975), done.
Checking connectivity... done.
Submodule path 'sources/externals': checked out '8c0a043783121b8d0115c5e8b306816fb348a082'
Cloning into 'sources/webcore'...
remote: Counting objects: 50321, done.
remote: Compressing objects: 100% (23603/23603), done.
remote: Total 50321 (delta 30989), reused 40553 (delta 23575)
Receiving objects: 100% (50321/50321), 32.13 MiB | 3.28 MiB/s, done.
Resolving deltas: 100% (30989/30989), done.
Checking connectivity... done.
Submodule path 'sources/webcore': checked out '893615eeb0e9a5318cbc17b9aab103e70b5c94dd'

```

thanks,
Available for more information.

**Comment by gcoeugnet** [comment]
Ok, in sources/extra/dependencies/, there's no Ubuntu_15.10... I'm gonna check the dependencies of ubuntu_15.04 to try to match ubuntu 15.10

**Comment by linkdd** [comment]
Now, Python will not be rebuilt so you're still having the Python without SSL support, my advice is to either:

 - do a fresh install
 - remove the files ``/opt/canopsis/var/lib/pkgmgr/packages/python.*`` to force the build-install to rebuild Python (it will believe that it hasn't been installed before)

**Comment by gcoeugnet** [comment]
Ok, fresh install with libssl and removal of previous python did the job. I'll make a pull request to propose an update of the doc cause at the moment it should be more like this : 
# apt-get install git-core
# git clone https://github.com/capensis/canopsis.git
# cd canopsis
# git submodule init
# git submodule update
# sh sources/extra/dependencies/_os_version_
# ./build-install.sh

Thanks for your time and quick answers.

**Comment by linkdd** [comment]
In fact, the ``sh sources/extra/dependencies/os_version`` is not needed because it is done by the build-install script.

**Comment by gcoeugnet** [comment]
Ok ! So an add of sources/extra/dependencies/ubuntu_15.10 should be a better proposal ;)
