### ISSUE TITLE
sudo ./build-install.sh = Error: Code: 1

### ISSUE THREAD

**Issue by dtreffot** [capensis/canopsis#230]
-- Build ...
-- Pre-install ...
Pre-install python-libs 0.6-0 ...
-- Install ...
Easy install Python Library: simplejson ...
Easy install Python Library: pymongo ...
Easy install Python Library: pycurl ...
Easy install Python Library: tornado ...
Easy install Python Library: python-daemon ...
Easy install Python Library: gevent ...
Easy install Python Library: bottle ...
Easy install Python Library: Beaker ...
Easy install Python Library: mongodb_beaker ...
Easy install Python Library: xmlrpclib ...
Easy install Python Library: pyparsing ...
Easy install Python Library: gunicorn ...
Easy install Python Library: apscheduler ...
Easy install Python Library: msgpack-python ...
Easy install Python Library: supervisor ...
Easy install Python Library: isit ...
Easy install Python Library: icalendar ...
Easy install Python Library: pytz ...
Easy install Python Library: kombu ...
Easy install Python Library: polib ...
Easy install Python Library: python-ldap ...
Error: Code: 1
Output:
Easy install failed ...

Installed /opt/canopsis/lib/python2.7/site-packages/polib-1.0.4-py2.7.egg
Processing dependencies for polib
Finished processing dependencies for polib
Searching for python-ldap
Best match: python-ldap 2.4.13
Processing python-ldap-2.4.13.tar.gz
Writing /tmp/easy_install-L8hzkc/python-ldap-2.4.13/setup.cfg
Running python-ldap-2.4.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-L8hzkc/python-ldap-2.4.13/egg-dist-tmp-UxmP5w
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
warning: no files found matching 'Makefile'
warning: no files found matching 'Modules/LICENSE'
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
In file included from Modules/LDAPObject.c:9:0:
Modules/errors.h:8:18: fatal error: lber.h: Aucun fichier ou dossier de ce type
compilation terminated.
defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R
extra_compile_args: 
extra_objects: 
include_dirs: /opt/openldap-RE24/include /usr/include/sasl /usr/include
library_dirs: /opt/openldap-RE24/lib /usr/lib
libs: ldap_r
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by Leryan** [comment]
Hello,

`lber.h` is an include file from OpenLDAP. Depending of your GNU/Linux distribution, can you try to install the openldap devel packages?

It *should* be `libldap-dev` for Debian and `openldap-devel` for RedHat/CentOS.

**Comment by dtreffot** [comment]
Hello,

They are already installed, when I see the error near openlap I had installed it

echosens@ossec:~$ uname -a
Linux ossec 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


![image](https://cloud.githubusercontent.com/assets/23218524/19960592/1d67cb36-a1ae-11e6-8695-43f1359bcea5.png)

Avalaible packet 
echosens@ossec:~$ sudo apt-cache search openldap
ldap-utils - OpenLDAP utilities
libldap-2.4-2 - OpenLDAP libraries
libldap-2.4-2-dbg - Debugging information for OpenLDAP libraries
libldap2-dev - OpenLDAP development libraries
slapd - OpenLDAP server (slapd)
slapd-dbg - Debugging information for the OpenLDAP server (slapd)
libsasl2-modules-ldap - Cyrus SASL - pluggable authentication modules (LDAP)
collectd-core - statistics collection and monitoring daemon (core system)
fusiondirectory-plugin-ppolicy - ppolicy overlay module plugin for FusionDirectory
golang-github-armon-gomdb-dev - LMDB for Go - OpenLDAP Lightning Memory-Mapped Database
golang-openldap-dev - OpenLDAP client integration for Go, using cgo
ldap-git-backup - Back up LDAP database in an Git repository
ldapscripts - Add and remove users and groups (stored in a LDAP directory)
libdbd-ldap-perl - Perl extension for LDAP access via an SQL/Perl DBI interface
liblmdb-dev - Lightning Memory-Mapped Database development files
liblmdb0 - Lightning Memory-Mapped Database shared library
libmozilla-ldap-perl - LDAP Perl module for the OpenLDAP C SDK
libnet-ldapapi-perl - Perl bindings for OpenLDAP C API
lmdb-dbg - Lightning Memory-Mapped Database debug files
lmdb-doc - Lightning Memory-Mapped Database doxygen documentation
lmdb-utils - Lightning Memory-Mapped Database Utilities
lua-ldap - LDAP library for the Lua language
python-django-python3-ldap - Django LDAP user authentication backend (Python2 version)
python-ldap - LDAP interface module for Python
python-ldap-dbg - LDAP interface module for Python (debug extension)
python-lmdb - Python binding for LMDB Lightning Memory-Mapped Database
python3-django-python3-ldap - Django LDAP user authentication backend (Python3 version)
python3-lmdb - Python 3 binding for LMDB Lightning Memory-Mapped Database
ruby-ldap - OpenLDAP library binding for Ruby
schema2ldif - Tool for converting OpenLDAP-style schemas to the LDIF format
smbldap-tools - Scripts to manage Unix and Samba accounts stored on LDAP
vbackup - modular backup utility
echosens@ossec:~$

Same Error 👍 
Using /opt/canopsis/lib/python2.7/site-packages/polib-1.0.4-py2.7.egg
Processing dependencies for polib
Finished processing dependencies for polib
Searching for python-ldap
Best match: python-ldap 2.4.13
Processing python-ldap-2.4.13.tar.gz
Writing /tmp/easy_install-k_pezn/python-ldap-2.4.13/setup.cfg
Running python-ldap-2.4.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-k_pezn/python-ldap-2.4.13/egg-dist-tmp-3CleVX
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
warning: no files found matching 'Makefile'
warning: no files found matching 'Modules/LICENSE'
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
Modules/LDAPObject.c:18:18: fatal error: sasl.h: Aucun fichier ou dossier de ce type
compilation terminated.
defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R
extra_compile_args: 
extra_objects: 
include_dirs: /opt/openldap-RE24/include /usr/include/sasl /usr/include
library_dirs: /opt/openldap-RE24/lib /usr/lib
libs: ldap_r
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by dtreffot** [comment]
sudo apt-get install libldap2-dev golang-openldap-dev libghc-ldap-dev libkf5ldap-dev libroot-net-ldap-dev lua-ldap-dev

Pre-install python-libs 0.6-0 ...
-- Install ...
Easy install Python Library: simplejson ...
Easy install Python Library: pymongo ...
Easy install Python Library: pycurl ...
Easy install Python Library: tornado ...
Easy install Python Library: python-daemon ...
Easy install Python Library: gevent ...
Easy install Python Library: bottle ...
Easy install Python Library: Beaker ...
Easy install Python Library: mongodb_beaker ...
Easy install Python Library: xmlrpclib ...
Easy install Python Library: pyparsing ...
Easy install Python Library: gunicorn ...
Easy install Python Library: apscheduler ...
Easy install Python Library: msgpack-python ...
Easy install Python Library: supervisor ...
Easy install Python Library: isit ...
Easy install Python Library: icalendar ...
Easy install Python Library: pytz ...
Easy install Python Library: kombu ...
Easy install Python Library: polib ...
Easy install Python Library: python-ldap ...
Easy install Python Library: validictory ...
Easy install Python Library: psutil==1.0.1 ...
Easy install Python Library: pybars ...
Easy install Python Library: PyMeta ...
Easy install Python Library: greenlet ...
Easy install Python Library: mock ...
Easy install Python Library: lxml ...
Error: Code: 1
Output:
Easy install failed ...


better after i have installed all the ldap-dev

**Comment by Leryan** [comment]
You don't need all these packages. The second error you had was related to SASL:

```
Modules/LDAPObject.c:18:18: fatal error: sasl.h: Aucun fichier ou dossier de ce type
```

Can you run those commands:

```
find /usr/include -name sasl.h

# from what you've got, run:
dpkg -S <result>

find /usr/include -name lber.h

# again, from results:
dpkg -S <result>
```

Thanks

**Comment by dtreffot** [comment]
@ossec:/opt/canopsis$ find /usr/include -name sasl.h
/usr/include/sasl/sasl.h
@ossec:/opt/canopsis$ dpkg -S /usr/include/sasl/sasl.h
libsasl2-dev: /usr/include/sasl/sasl.h
@ossec:/opt/canopsis$ find /usr/include -name lber.h
/usr/include/lber.h
@ossec:/opt/canopsis$ dpkg -S /usr/include/lber.h
libldap2-dev:amd64: /usr/include/lber.h
@ossec:/opt/canopsis$

**Comment by dtreffot** [comment]
ok too for this one
@ossec:/opt/canopsis$ dpkg -S /usr/include/libxml2/libxml/xmlversion.h
libxml2-dev:amd64: /usr/include/libxml2/libxml/xmlversion.h

**Comment by Leryan** [comment]
Ok, see, you need only `libsasl2-dev` to fix the second error. But it's strange this dependency wasn't already installed though.

**Comment by dtreffot** [comment]
Another one and here no idea 👍 


Searching for requests
Best match: requests 1.1.0
Processing requests-1.1.0.tar.gz
Writing /tmp/easy_install-49Dms1/requests-1.1.0/setup.cfg
Running requests-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-49Dms1/requests-1.1.0/egg-dist-tmp-e5iXPN
Traceback (most recent call last):
  File "/opt/canopsis/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==20.2.2', 'console_scripts', 'easy_install')()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 2244, in main
  File "/opt/canopsis/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/canopsis/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/canopsis/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 391, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 853, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1081, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1067, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 246, in run_setup
  File "/opt/canopsis/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "/opt/canopsis/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 166, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 141, in resume
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 154, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 243, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 273, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 242, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-49Dms1/requests-1.1.0/setup.py", line 6, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/__init__.py", line 52, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/utils.py", line 23, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/compat.py", line 7, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/packages/__init__.py", line 3, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/packages/urllib3/__init__.py", line 16, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/packages/urllib3/connectionpool.py", line 45, in <module>
  File "/tmp/easy_install-49Dms1/requests-1.1.0/requests/packages/urllib3/util.py", line 293, in <module>
NameError: name 'CERT_NONE' is not defined

**Comment by Leryan** [comment]
Well… this error should be fixed since we upgraded Python to 2.7.11.

Could you run this:

```
su - canopsis
python
# now from the python console

import ssl
help(ssl)
```

Please paste the entire `NAME`, `FILE` and `DESCRIPTION`  sections.

**Comment by dtreffot** [comment]
Python 2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> help(ssl)
Help on module ssl:

NAME
    ssl - This module provides some more Pythonic support for SSL.

FILE
    /usr/lib/python2.7/ssl.py

MODULE DOCS
    http://docs.python.org/library/ssl

DESCRIPTION
    Object types:

      SSLSocket -- subtype of socket.socket which does SSL over the socket

    Exceptions:

      SSLError -- exception raised for I/O errors

    Functions:

      cert_time_to_seconds -- convert time string used for certificate
                              notBefore and notAfter functions to integer
                              seconds past the Epoch (the time values
                              returned from time.time())

      fetch_server_certificate (HOST, PORT) -- fetch the certificate provided
                              by the server running on HOST at port PORT.  No
                              validation of the certificate is performed.

    Integer constants:

    SSL_ERROR_ZERO_RETURN
    SSL_ERROR_WANT_READ
    SSL_ERROR_WANT_WRITE
    SSL_ERROR_WANT_X509_LOOKUP
    SSL_ERROR_SYSCALL
    SSL_ERROR_SSL
    SSL_ERROR_WANT_CONNECT

    SSL_ERROR_EOF
    SSL_ERROR_INVALID_ERROR_CODE

    The following group define certificate requirements that one side is
    allowing/requiring from the other side:

    CERT_NONE - no certificates from the other side are required (or will
                be looked at if provided)
    CERT_OPTIONAL - certificates are not required, but if provided will be
                    validated, and if validation fails, the connection will
                    also fail
    CERT_REQUIRED - certificates are required, and will be validated, and
                    if validation fails, the connection will also fail

    The following constants identify various SSL protocol variants:

    PROTOCOL_SSLv2
    PROTOCOL_SSLv3
    PROTOCOL_SSLv23
    PROTOCOL_TLSv1
    PROTOCOL_TLSv1_1
:

**Comment by Leryan** [comment]
Ew, this isn't canopsis's python interpreter. You've launched the system one. The canopsis "virtualenv" might not be fully ready at this installation stage. Did you run `su - canopsis` before?

If yes, give a try with `/opt/canopsis/bin/python2.7`.

**Comment by Leryan** [comment]
I forgot to tell you one thing: Ubuntu isn't a supported platform, but it's something interesting to see what happen on other platforms and improve portability.

**Comment by dtreffot** [comment]
ok :-) maybe this is the problem so 


Here from canopsis user 👍 
@ossec:~$ su - canopsis
Mot de passe :
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

[canopsis@ossec ~]$ cd /opt
[canopsis@ossec opt]$ cd canopsis/
[canopsis@ossec ~]$ python
Python 2.7.11 (default, Nov  2 2016, 17:20:42)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/canopsis/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
>>> help(ssl)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ssl' is not defined
>>>

**Comment by Leryan** [comment]
Okay! I know the problem: the `ssl` module wasn't built because of some incompatibility with the `openssl` library Ubuntu is shipping.

I cannot do anything for this problem right now but recommanding you to make a install on Debian 8 if you want to stay on a deb-based distribution.

**Comment by dtreffot** [comment]
It's ok after doing this the following thing but get another error 👍 


Easy install Python Library: requests ...
Error: Code: 1
Output:
Easy install failed ...
[canopsis@ossec ~]$ pip install requests
Collecting requests
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 1.7MB/s
Installing collected packages: requests
Successfully installed requests-2.9.1
You are using pip version 8.1.1, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[canopsis@ossec ~]$ pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 421kB/s
Installing collected packages: pip
Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[canopsis@ossec ~]$ sudo pip install --upgrade pip
The directory '/opt/canopsis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/opt/canopsis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading pip-9.0.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 407kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[canopsis@ossec ~]$ sudo pip install requests
The directory '/opt/canopsis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/opt/canopsis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[canopsis@ossec ~]$ sudo ldconfig
[canopsis@ossec ~]$ ls
bin  binaries  build-install.sh  build_messages.txt  doc  etc  include  lib  log  opt  README.md  share  sources  tmp  tools  var
[canopsis@ossec ~]$ cd ..
[canopsis@ossec opt]$ ls
canopsis    graylog-web-interface            observium                          ossec-hids-2.8.3.tar.gz        rrdtool_1.6.0.orig.tar.gz  zabbix-release_3.0-1+xenial_all.deb
debian      graylog-web-interface-1.3.4      observium-community-latest.tar.gz  ossec-wui-0.8                  rrdtool-1.x-1.6.0          zabbix-release_3.0-1+xenial_all.deb.1
dotdeb.gpg  graylog-web-interface-1.3.4.tgz  ossec-hids-2.8.3                   rrdtool_1.6.0-1.debian.tar.xz  v0.8.tar.gz
[canopsis@ossec opt]$ ls -al
total 103384
drwxr-xr-x  9 root     root         4096 nov.   2 17:10 .
drwxr-xr-x 24 root     root         4096 oct.  31 14:00 ..
drwxr-xr-x 19 canopsis canopsis     4096 nov.   3 12:13 canopsis
drwxr-xr-x  4 root     root         4096 mai    3  2016 debian
-rw-r--r--  1 root     root         5299 juil. 27  2010 dotdeb.gpg
lrwxrwxrwx  1 root     root           27 oct.  25 09:36 graylog-web-interface -> graylog-web-interface-1.3.4
drwxr-xr-x  6 ossec    ossec        4096 oct.  25 09:44 graylog-web-interface-1.3.4
-rw-r--r--  1 root     root     41632011 mars  16  2016 graylog-web-interface-1.3.4.tgz
drwxrwxrwx 12 www-data www-data     4096 oct.  27 15:12 observium
-rw-r--r--  1 root     root     61239194 sept. 30 22:53 observium-community-latest.tar.gz
drwxrwxr-x  8 root     root         4096 oct.  20 17:20 ossec-hids-2.8.3
-rw-r--r--  1 root     root      1642095 nov.   5  2015 ossec-hids-2.8.3.tar.gz
drwxrwxr-x  2 root     root         4096 oct.  21 09:19 ossec-wui-0.8
-rw-r--r--  1 root     root        27704 oct.  27 14:05 rrdtool_1.6.0-1.debian.tar.xz
-rw-r--r--  1 root     root      1101128 oct.  27 14:09 rrdtool_1.6.0.orig.tar.gz
drwxrwxr-x 13 root     root         4096 oct.  27 14:30 rrdtool-1.x-1.6.0
-rw-r--r--  1 root     root       163698 oct.  20 17:21 v0.8.tar.gz
-rw-r--r--  1 root     root         3842 juil. 19 06:57 zabbix-release_3.0-1+xenial_all.deb
-rw-r--r--  1 root     root         3842 juil. 19 06:57 zabbix-release_3.0-1+xenial_all.deb.1
[canopsis@ossec opt]$ sudo chown -R canopsis.canopsis canopsis/
[canopsis@ossec opt]$ cd canopsis/
[canopsis@ossec ~]$ sudo ./build-install.sh
Linux Distribution:
Dist found
ubuntu
16.04
Install OS dependencies for ubuntu 16.04 ...
 + Impossible to find dependencies file (/opt/canopsis/sources/extra/dependencies/ubuntu_16)...
 + Fix env vars ...
################################################################
#
# Package: canohome v0.6-r0 (ubuntu-16.04 x86_64)
# Date: jeudi 3 novembre 2016, 12:15:25 (UTC+0100)
#
################################################################

-- Pre-update ...
Pre-update canohome 0.6-0 ...
-- Update ...
-- Archiving files...
-- Extracting files...
-- Fix permissions
-- Update config files
Ignoring file: ./etc/canopsis-version
Ignoring file: ./etc/init.d/.gitignore
-- Cleaning
-- Post-update ...
Post-update canohome 0.6-0 ...
-- Listing files ...

################################################################
#
# Package: ssl-conf v0.1-r0 (ubuntu-16.04 x86_64)
# Date: jeudi 3 novembre 2016, 12:15:26 (UTC+0100)
#
################################################################

-- Pre-update ...
-- Update ...

===> Generating CA...

Generating a 1024 bit RSA private key
..++++++
..............................++++++
unable to write 'random state'
writing new private key to '/opt/canopsis/etc/ssl/cakey.pem'
-----

===> Generating server certificate...

Generating a 1024 bit RSA private key
....................................................................++++++
.......................................................................++++++
unable to write 'random state'
writing new private key to '/opt/canopsis/etc/ssl/key.pem'
-----

===> Signing server certificate...

Using configuration from /opt/canopsis/etc/ssl/openssl.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 22 (0x16)
        Validity
            Not Before: Nov  3 11:15:27 2016 GMT
            Not After : Nov  3 11:15:27 2017 GMT
        Subject:
            countryName               = FR
            stateOrProvinceName       = France
            organizationName          = Capensis
            organizationalUnitName    = Canopsis
            commonName                = cpsnode
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Subject Key Identifier:
                EA:1E:83:30:75:19:CD:87:95:F2:F1:FD:19:D1:0C:AD:58:60:9E:39
            X509v3 Authority Key Identifier:
                keyid:23:17:72:8C:8D:2D:85:C9:44:57:0C:1A:BE:17:24:7C:4D:8E:9F:7A

Certificate is to be certified until Nov  3 11:15:27 2017 GMT (365 days)

Write out database with 1 new entries
Data Base Updated
unable to write 'random state'

===> Generate bundles...


===> Fix permissions...

-- Post-update ...
-- Listing files ...

################################################################
#
# Package: python v2.7.11-r1 (ubuntu-16.04 x86_64)
# Date: jeudi 3 novembre 2016, 12:15:27 (UTC+0100)
#
################################################################

-- Pre-update ...
Pre-update python 2.7.11-1 ...
-- Update ...
-- Post-update ...
Post-update python 2.7.11-1 ...
-- Listing files ...

################################################################
#
# Package: python-libs v0.6-r0 (ubuntu-16.04 x86_64)
# Date: jeudi 3 novembre 2016, 12:15:28 (UTC+0100)
#
################################################################

-- Build ...
-- Pre-install ...
Pre-install python-libs 0.6-0 ...
-- Install ...
Easy install Python Library: simplejson ...
Easy install Python Library: pymongo ...
Easy install Python Library: pycurl ...
Easy install Python Library: tornado ...
Easy install Python Library: python-daemon ...
Easy install Python Library: gevent ...
Easy install Python Library: bottle ...
Easy install Python Library: Beaker ...
Easy install Python Library: mongodb_beaker ...
Easy install Python Library: xmlrpclib ...
Easy install Python Library: pyparsing ...
Easy install Python Library: gunicorn ...
Easy install Python Library: apscheduler ...
Easy install Python Library: msgpack-python ...
Easy install Python Library: supervisor ...
Easy install Python Library: isit ...
Easy install Python Library: icalendar ...
Easy install Python Library: pytz ...
Easy install Python Library: kombu ...
Easy install Python Library: polib ...
Easy install Python Library: python-ldap ...
Easy install Python Library: validictory ...
Easy install Python Library: psutil==1.0.1 ...
Easy install Python Library: pybars ...
Easy install Python Library: PyMeta ...
Easy install Python Library: greenlet ...
Easy install Python Library: mock ...
Easy install Python Library: lxml ...
Easy install Python Library: requests ...
Easy install Python Library: supervisor-wildcards ...
Easy install Python Library: RestrictedPython ...
Easy install Python Library: six ...
Easy install Python Library: influxdb ...
Easy install Python Library: extras ...
Easy install Python Library: fixtures ...
Easy install Python Library: funcsigs ...
Easy install Python Library: fuzzywuzzy ...
Easy install Python Library: lettuce ...
Easy install Python Library: linecache2 ...
Easy install Python Library: pbr ...
Easy install Python Library: pyrsistent ...
Easy install Python Library: python-mimeparse ...
Easy install Python Library: python-subunit ...
Easy install Python Library: sure ...
Easy install Python Library: testtools ...
Easy install Python Library: traceback2 ...
Easy install Python Library: unittest2 ...
Easy install Python Library: chardet ...
 + Install conf file 'supervisord.conf' ...
-- Post-install ...
Post-install python-libs 0.6-0 ...
-- Listing files ...

################################################################
#
# Package: ubik v0.1.8-r1 (ubuntu-16.04 x86_64)
# Date: jeudi 3 novembre 2016, 12:16:04 (UTC+0100)
#
################################################################

-- Build ...
-- Pre-install ...
Pre-install ubik 0.1.8-1 ...
-- Install ...
Easy install Python Library: /opt/canopsis/sources/externals/Ubik.tgz ...
Error: Code: 1
Output:
Easy install failed ...
[canopsis@ossec ~]$

**Comment by dtreffot** [comment]
in the same way 👍 

[canopsis@ossec ~]$ pip install ubik
Collecting ubik
  Downloading ubik-0.2.6.tar.gz (138kB)
    100% |████████████████████████████████| 143kB 1.9MB/s
Collecting progressbar==2.3 (from ubik)
  Downloading progressbar-2.3.tar.gz
Collecting requests==1.1.0 (from ubik)
  Downloading requests-1.1.0.tar.gz (337kB)
    100% |████████████████████████████████| 337kB 1.6MB/s
Collecting docopt==0.5.0 (from ubik)
  Downloading docopt-0.5.0.tar.gz
Collecting isit==0.3.5 (from ubik)
  Downloading isit-0.3.5.tar.gz
Building wheels for collected packages: ubik, progressbar, requests, docopt, isit
  Running setup.py bdist_wheel for ubik ... done
  Stored in directory: /opt/canopsis/.cache/pip/wheels/f6/57/ba/2082dcc0ee38e36c9cb0fd63ed98825b627fd464c47702cc6f
  Running setup.py bdist_wheel for progressbar ... done
  Stored in directory: /opt/canopsis/.cache/pip/wheels/5e/5f/94/5a6203a7df123c64c9650d2325906620af9ddbd2dff26989d8
  Running setup.py bdist_wheel for requests ... done
  Stored in directory: /opt/canopsis/.cache/pip/wheels/fb/ca/3a/e9c7765896d6dfed463dade1cd5c9aac9596905993ebf084dc
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /opt/canopsis/.cache/pip/wheels/29/d0/b2/7030c2b3a23be1986a83dc023919b9101216ef1a7a3a5534c7
  Running setup.py bdist_wheel for isit ... done
  Stored in directory: /opt/canopsis/.cache/pip/wheels/03/75/3f/fe164af094594f42988adb258a429866f03018ecff0d46c9aa
Successfully built ubik progressbar requests docopt isit
Installing collected packages: progressbar, requests, docopt, isit, ubik
Successfully installed docopt-0.5.0 isit-0.3.5 progressbar-2.3 requests-2.9.1 ubik-0.2.6
You are using pip version 8.1.1, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


but now 👍

**Comment by dtreffot** [comment]
################################################################
#
# Package: canolibs v0.8-r0 (ubuntu-16.04 x86_64)
# Date: jeudi 3 novembre 2016, 12:21:34 (UTC+0100)
#
################################################################

-- Build ...
-- Pre-install ...
Pre-install canolibs 0.8-0 ...
-- Install ...
-- Install project: common
-- Install project: old
-- Install project: configuration
-- Install project: timeserie
-- Install project: middleware
-- Install project: task
-- Install project: rpc
-- Install project: mom
-- Install project: storage
-- Install project: mongo
-- Install project: schema
-- Install project: ctxprop
-- Install project: event
-- Install project: kombu
Error: Code: 1
Output:
Impossible to install kombu
[canopsis@ossec ~]$

**Comment by Leryan** [comment]
This is… really strange.

Can you give us full details:

 * Full OS version
 * A list of external repositories configured if any: watch in `/etc/apt/sources.list` and `/etc/apt/sources.list.d/`
 * The current git branch you're using to install: `git branch`
 * The current git commit you're using to install: `git log --pretty=format:'%H' -n 1`
 * Full output of `dpkg -l`. Use a paste service, like https://gist.github.com
 * Is this a fresh install or you tried to install many times, or is it an upgrade?
 * Can you eventually try a canopsis install on a fresh, minimal system install?

Be careful about any private information you may not want to share.

These informations will help us to show any difference between your setup and our.

I'll try to update this issue by making a fresh install and see what happen.

Thanks.

**Comment by dtreffot** [comment]
https://gist.github.com/dtreffot/2c79b70efb72003793dcf6467c696a29
