### ISSUE TITLE
canopsis-filldb import error

### ISSUE THREAD

**Issue by kamel1234** [capensis/canopsis#232]
I'm installing Canopsis, i got error below. can you help on that

Traceback (most recent call last):
  File "/opt/canopsis/bin/canopsis-filldb", line 4, in <module>
    __import__('pkg_resources').run_script('canopsis.migration==0.1', 'canopsis-filldb')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.migration-0.1-py2.7.egg/EGG-INFO/scripts/canopsis-filldb", line 34, in <module>
    mgr = MigrationTool()
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/canopsis/configuration/configurable/__init__.py", line 59, in __call__
    result.apply_configuration(conf=conf)
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/canopsis/configuration/configurable/__init__.py", line 437, in apply_configuration
    drivers=drivers, override=override
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/canopsis/configuration/configurable/__init__.py", line 487, in get_configuration
    conf_path=conf_path, logger=logger, drivers=drivers
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/canopsis/configuration/configurable/__init__.py", line 747, in _get_driver
    driver = ConfigurationDriver.get_driver(driver)
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/canopsis/configuration/driver/__init__.py", line 287, in get_driver
    result = lookup(path)
  File "/opt/canopsis/lib/python2.7/site-packages/canopsis.common-0.1-py2.7.egg/canopsis/common/utils.py", line 243, in lookup
    ae
ImportError: Wrong path canopsis.configuration.driver.file.json.JSONConfigurationDriver at ['canopsis', 'configuration', 'driver', 'file'], errors when importing module canopsis.configuration.driver.file.json : No module named decoder, 'module' object has no attribute 'json'
Error: Code: 1
Output:
Error in command 'canopsis-filldb --init'...

**Comment by Leryan** [comment]
Hello

Tell us which version you're using please. Did you cloned from master or develop?

Thanks

**Comment by kamel1234** [comment]
master

**Comment by Leryan** [comment]
Ok, master hasn't changed for many times now, switch to `develop` or you may want to use release tags such as the latest `2.5.5`.

But this isn't on github for now, synchronization with our main repository will be restored soon.

Please checkout from this repo: https://git.canopsis.net/canopsis/canopsis

**Comment by kamel1234** [comment]
I installed the latest release Master. but i have the same issue.

**Comment by Leryan** [comment]
If you're doing a fresh install, please proceed as follow, as root user:

```
pkill -u -9 canopsis
rm -rf /opt/canopsis

rm -rf canopsis
git clone https://git.canopsis.net/canopsis/canopsis.git
cd canopsis
git checkout 2.5.5
./build-install.sh

su - canopsis -c "hypcontrol start"
```

**Comment by kamel1234** [comment]
i followed the steps above
got a message that "mongodb : EROR (no such file)". 
seems that mongodb is not installed as nothing under /opt/canopsis and also I can not find it under source/externals

**Comment by Leryan** [comment]
MonogDB is now installed from packages, as for erlang.

I don't understand your error. Paste full log.

**Comment by Leryan** [comment]
Hello @kamel1234 

I got the same error as you and this was because of an old mongodb source list installed.

Please do:

```
grep -rn mongo /etc/apt*
```

Then remove any file given by grep output, and re-run build-install.sh
