### ISSUE TITLE
amqp2engines qui ne démarrent pas

### ISSUE THREAD

**Issue by jdmsilbvs** [capensis/canopsis#234]
Bonjour,

En lançant hypcontrol status, j'ai 3 erreurs fatales : 
ubuntu 14.04.5
canopsis branche develop sur https://git.canopsis.net à jour

Je ne récupère donc pas le statut ack lorsqu'il est défini sur Nagios, je ne peux pas non plus acquitté un évènement sur canopsis.

**amqp2engines:engine-acknowledgement-0         FATAL     Exited too quickly (process log may have details)**
la collection ack dans mongo est vide
#######_tail -f /opt/canopsis/var/log/engines/acknowledgement.log_

Traceback (most recent call last):
  File "/opt/canopsis/bin/engine-launcher", line 224, in <module>
    args.etype, args.name, args.procnum, args.loglevel.upper())
  File "/opt/canopsis/bin/engine-launcher", line 98, in __init__
    self.load_engine_config()
  File "/opt/canopsis/bin/engine-launcher", line 156, in load_engine_config
    for item in config.items(self.section):
  File "/opt/canopsis/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'engine:acknowledgement'
#######

**amqp2engines:engine-cancel-0                  FATAL     Exited too quickly (process log may have details)**
#######_tail -f /opt/canopsis/var/log/engines/cancel.log_

Traceback (most recent call last):
  File "/opt/canopsis/bin/engine-launcher", line 224, in <module>
    args.etype, args.name, args.procnum, args.loglevel.upper())
  File "/opt/canopsis/bin/engine-launcher", line 98, in __init__
    self.load_engine_config()
  File "/opt/canopsis/bin/engine-launcher", line 156, in load_engine_config
    for item in config.items(self.section):
  File "/opt/canopsis/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'engine:cancel'
########

**amqp2engines:engine-stats-0                   FATAL     Exited too quickly (process log may have details)**
########_tail -f /opt/canopsis/var/log/engines/stats.log_

Traceback (most recent call last):
  File "/opt/canopsis/bin/engine-launcher", line 224, in <module>
    args.etype, args.name, args.procnum, args.loglevel.upper())
  File "/opt/canopsis/bin/engine-launcher", line 98, in __init__
    self.load_engine_config()
  File "/opt/canopsis/bin/engine-launcher", line 156, in load_engine_config
    for item in config.items(self.section):
  File "/opt/canopsis/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'engine:stats'
########

**Comment by arctarus44** [comment]
Bonjour.

Contrairement à ce qui est écrit dans la documentation, ubuntu n'est plus supporté officiellement. Tu peux toujours trouver les fichiers d'installations adéquates dans le repo. Mais ils y a de forte chance qu'ils ne soient plus directement fonctionnels, de nombreuses modifications ont été apportées ces derniers mois pour moderniser canopsis

Les engines en question sont retirés de la chaine d'engines, par conséquent ils ne sont pas utiles au fonctionnement de canopsis et ne devrait pas êtres démarré. Les erreurs que tu observes dans les log sont le résultat de ce nettoyage.

Néanmoins, ne pas pouvoir acquitter une alarme n'est pas normal. Est-ce que tu peux nous détailler comment tu as voulu acquitter une alarme ? Et nous fournir un exemple d'événement nagios envoyé lors d'un acquittement ?

**Comment by jdmsilbvs** [comment]
Bonjour,

Acquittement d'un problème depuis l'interface web du serveur Nagios 4.3.4 (connecteur neb2amqp-4x)
dans nagios.log :
############
[[1518421492] EXTERNAL COMMAND: ACKNOWLEDGE_SVC_PROBLEM;nomdhotedansnagios;Aggregat;1;0;0;Tech responsable site;Test envoi acquittement Nagios
[1518421492] neb2amqp: acktype: 1700
[1518421492] neb2amqp: Addind acknowledgement
[1518421494] neb2amqp: FIFO: Up to date
############
Sur le serveur canopsis, je ne vois rien arriver dans /var/log/engines/eventstore.log

Dans l'ancienne version, l'évènement était bien marqué acquitté (violet), l'utilisateur "tech responsable site" apparaissait, par contre je n'avais pas le message renseigné lors de l'acquittement (ici : Test envoi acquittement Nagios). Je pouvais également cliquer sur le bouton ack en face d'une alerte. Actuellement, la fenêtre apparait me permettant de renseigner la raison de l'acquittement mais après validation, l'état reste le même. 

Pour l'installation j'ai utilisé /sources/extra/dependencies/debian9, j'avais relevé qu'ubuntu 14.04 était non supporté. Je vais surement refaire une install sur une debian9, mais est-ce possible de faire une migration pour récupérer les tableaux de bord, sélecteurs.. déjà construits ?

Bonne journée !

**Comment by Leryan** [comment]
Bonjour,

Pour récupérer la totalité de vos données, il vous faudra faire une sauvegarde et restoration de la base mongodb.

Nous avons récemment créé de la documentation à ce sujet:

https://git.canopsis.net/canopsis/canopsis/blob/develop/doc/docs/fr/guide_administrateur/dump_restore.md

En ce qui concerne les acquitements, on est en train de changer pour le bac à alarme… qui pour l’instant n’est pas public. Nous allons nous en occuper très rapidement car de toute façon on en a besoin pour les process de build chez nous… vraiment désolé pour la gêne, la branche develop porte bien son nom.

Pour l’instant vous pouvez réactiver l’engine akcnowledgement en reprenant les parties concernées dans d’anciennes versions de `etc/amqp2engines.conf` et `etc/supervisord.d/amqp2engines.conf`.

L’un démarre l’engine, l’autre permet de lui faire suivre les évènements.

On vous tient au courant pour le bac à alarme.
